# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


Vagrant.configure("2") do |config|

	config.vm.define "dockerhost" do |dockerhost|
		dockerhost.vm.box = "ubuntu/xenial64"
		dockerhost.vm.hostname = "m300-host"
		dockerhost.vm.network "private_network", ip: "192.168.2.100"
			dockerhost.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
			dockerhost.vm.provider "virtualbox" do |vb|
				vb.memory = "512"
			end
		dockerhost.vm.synced_folder "./M300", "/vagrant"
	end	
end